### PR TITLE
Update version of thinreports gem

### PR DESCRIPTION
**Pull request by tanaka51**
Hi,

I updated version of gem https://github.com/thinreports/thinreports-generator .
This enables to use Thinreport Editor 0.8.0 with Rails.

Thanks.

### CODE REVIEW

**Comment by tanaka51** [comment]
oops, test failed...

I'll fix tests later.

**Comment by kakipo** [comment]
great job :+1:

**Comment by hidakatsuya** [comment]
:+1:

**Comment by kakipo** [comment]
@takeshinoda 
Any progress?
I hope you review this PR.

**Comment by eccyan** [comment]
:+1:

**Comment by takeshinoda** [comment]
Sorry, I did not notice this PR for a long time. Please wait few days ...

**Comment by takeshinoda** [comment]
Sorry to keep you waiting. Thank you.

**Comment by takeshinoda** [comment]
Release 0.2.0.
https://rubygems.org/gems/thinreports-rails/versions/0.2.0

**Comment by tanaka51** [comment]
I'm glad to merge this PR! Thank you!

**Pull request merged**
